name: deploy-prod

on:
  repository_dispatch:
    types: [trigger-workflow]
  push:
    branches:
      - main
    paths-ignore:
      - 'integration-api-default-config.json'
      - 'README.md'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '12.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # adding all the prod regions to region matrix below
        region: [westeurope, germanywestcentral, eastus, canadacentral, australiaeast]
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Get credentials
        uses: leanix/secrets-action@master
        with:
          secret-store-credentials: ${{ secrets.INJECTED_SECRET_STORE_CREDENTIALS }}

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }} 

      - name: 'Login to Prod via Azure CLI'
        if: github.ref=='refs/heads/main'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}


      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd
          
      - name: 'Deploy Azure Function to Prod'
        if: github.ref=='refs/heads/main'
        uses: Azure/functions-action@v1
        env:
          # creating an env varibale on the step, each region from the above matrix will be replaced
          AZURE_FUNCTIONAPP_NAME_PROD: functions-${{ matrix.region }}-prod-githubrepositoryconnector
        with:
          # using the above created variable as the func app name
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_PROD }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: LeanIX Jira Release Tracking
        if: github.ref=='refs/heads/main'
        uses: leanix/jira-action@master
        with:
          environment: 'prod'

      - name: Microservice Intelligence Tracking
        if: github.ref=='refs/heads/main'
        uses: leanix/microservice-intelligence-action@master
