name: notification

on:
  workflow_run:
    workflows:
      - deploy-prod
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send CI/CD pipeline success message
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ env.SLACK_TOKEN }}
          slack-channel: '#mi-connectors-notifications'
          slack-text: |
            :beers: ${{ github.repository }} successfully deployed!

      - name: Send CI/CD pipeline failure message
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ env.SLACK_TOKEN }}
          slack-channel: '#mi-connectors-notifications'
          slack-text: |
            :no_entry_sign: :beers: ${{ github.repository }} failed to deploy!
